### ISSUE TITLE
Various errors with any theme

### ISSUE THREAD

**Issue by p3lim** [Antergos/web-greeter#109]
Trying to get LightDM set up on my laptop, been running into various issues with every theme I've tried to use, including the two that it comes with.
When running with `lightdm-webkit2-greeter` and the theme "antergos" I get this:
```
** (WebKitWebProcess:1163): CRITICAL **: lightdm_greeter_ensure_shared_data_dir_sync: assertion 'priv->connected' failed
undefined:13824:37: CONSOLE ERROR: TypeError: null is not an object (evaluating 'user_data_dir.substr')
```
At which point it will ask to load default or fallback theme.
When using the "simple" theme I get this:
```
file:///usr/share/lightdm-webkit/themes/simple/index.html:194:10: CONSOLE ERROR ReferenceError: Can't find variable: lightdm
```

Configs for both lightdm and lightdm-webkit2-greeter are stock, except for setting the correct greeter in `/etc/lightdm/lightdm.conf` and the theme in `/etc/lightdm/lightdm-webkit2-greeter.conf`.
Running `lightdm --test-mode --debug` flashes an empty window on the screen then closes, lots of errors about permission denied. Elevating this results in a black screen w/ blinking cursor, have to force reset at this point.

Versions/OS:

- archlinux x86_64, everything up-to-date at time of posting
- lightdm: 1:1.20.0
- lightdm-webkit2-greeter: 2.2.2 (AUR)
- webkit2gtk: 2.14.3

I'll supply logs if needed, just tell me which one(s).

**Comment by lots0logs** [comment]
Hi, did you install it using the PKGBUILD in the AUR? It looks like there's an issue with the shared data directory (typically this is located at `/var/lib/lightdm-data/$username`. Does that directory exist on your system?

**Comment by p3lim** [comment]
Yes, used the PKGBUILD from AUR to install it, that directory exists.

**Comment by lots0logs** [comment]
Could you try installing using the commit I just made and let me know the result? You can do it using this updated PKGBUILD in the place of the one in the AUR: http://paste2.org/ItHzk8K0

**Comment by p3lim** [comment]
Still getting the same errors, build went fine tho'.

**Comment by lots0logs** [comment]
That shouldnt be possible. Did you bump the pkgrel when you built it?

**Comment by p3lim** [comment]
Yep

**Comment by p3lim** [comment]
Just tested the second commit, still the same.

**Comment by lots0logs** [comment]
This error is no longer possible with the latest commit:
```
CONSOLE ERROR: TypeError: null is not an object (evaluating 'user_data_dir.substr')
```
There is a bug in `glib-compile-resources` where it doesnt notice changes to gresource files during subsequent builds. Are you reusing the same build directory? If so, try removing it completely and then rebuilding.

**Comment by lots0logs** [comment]
Could you post the full contents of `lightdm.log` and `x-0-greeter.log` if the issue still occurs? Thanks.

**Comment by p3lim** [comment]
I stopped getting this error:

    CONSOLE ERROR: TypeError: null is not an object (evaluating 'user_data_dir.substr')

And instead it let me know that `/usr/share/backgrounds` didn't exist, which I've now made.
The "antergos" theme still gets javascript exceptions (no detail in the output from `lightdm-webkit2-greeter`), and the "simple" theme still gets the same errors as before.

Here is the entire contents of `/var/log/lightdm/`: https://gist.github.com/p3lim/733e961e5e6c9742b9114c92a88e4062

**Comment by lots0logs** [comment]
Could you enable debug mode in the config file and then check the webkit dev console inside the greeter (Right-Click>>Inspect Element>>Console)

**Comment by p3lim** [comment]
With debug mode on I'm unable to right-click when using the antergos theme.
When I mouse over anything in the dev console it turns black, this was on the simple theme (only one I could seem to get a context menu on).

If I left-click anywhere in either theme the whole screen goes black (cursor still visible, right-clicking doesn't seem to work).

**Comment by FallingSnow** [comment]
Same issue. Greeter locks up when attempting to open devtools.

```
$ lightdm-webkit2-greeter
file:///usr/share/lightdm-webkit/themes/material2/bundle.js:1:831: CONSOLE DEBUG Loading Theme

** (WebKitWebProcess:3833): CRITICAL **: lightdm_greeter_ensure_shared_data_dir_sync: assertion 'priv->connected' failed
file:///usr/share/lightdm-webkit/themes/material2/bundle.js:66:4550: CONSOLE DEBUG Main loaded. [object Object]
file:///usr/share/lightdm-webkit/themes/material2/bundle.js:65:15438: CONSOLE DEBUG App loaded. [object Object]
file:///usr/share/lightdm-webkit/themes/material2/bundle.js:65:19748: CONSOLE DEBUG Background loaded. [object Object]
file:///usr/share/lightdm-webkit/themes/material2/bundle.js:65:21133: CONSOLE DEBUG Updated background. random-image
file:///usr/share/lightdm-webkit/themes/material2/bundle.js:65:21360: CONSOLE DEBUG Clock Locale set to: en
file:///usr/share/lightdm-webkit/themes/material2/bundle.js:66:24332: CONSOLE DEBUG RandomImage loaded. [object Object]
file:///usr/share/lightdm-webkit/themes/material2/bundle.js:39:7488: CONSOLE DEBUG Image loaded. [object Object]
file:///usr/share/lightdm-webkit/themes/material2/bundle.js:65:29165: CONSOLE DEBUG Login loaded. [object Object]
file:///usr/share/lightdm-webkit/themes/material2/bundle.js:65:23449: CONSOLE DEBUG Footer loaded. [object Object]
file:///usr/share/lightdm-webkit/themes/material2/bundle.js:65:25504: CONSOLE WARN Hibernate not supported.

(lightdm-webkit2-greeter:3822): Gtk-WARNING **: Allocating size to WebKitWebViewBase 0x561a9b0fc380 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

** (lightdm-webkit2-greeter:3822): WARNING **: Error running javascript: An exception was raised in JavaScript
```

**Comment by lots0logs** [comment]
I think the devtools issue is a bug in webkitgtk actually. I remember seeing an email from the mailing list not too long ago.

**Comment by p3lim** [comment]
Tried running my theme in Antergos under VM, failed to run and the devtools are black there too.
Here's a link to my (rather simple) theme: https://gist.github.com/p3lim/bc778538c9edb6eb9ef69d09d6dfb72e

Works fine with a mock that follows the API, fails to run under lightdm.
