### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by Kaspichhh** [Antergos/web-greeter#110]
The last update solved my issue #106 on one pc, but on other pc I am getting this when logging out, and after restart or pc had been shut down for a while, I am getting only black screen and cursor. 

(lightdm-webkit2-greeter:2795): Gtk-CRITICAL **: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed

(lightdm-webkit2-greeter:2795): Gdk-WARNING **: lightdm-webkit2-greeter: Fatal IO error 4 (Interrupted system call) on X server :0.

**Comment by lots0logs** [comment]
I'm afraid that what you've provided is not useful. I need to see the full logs: lightdm, greeter, and systemd journal.
