### ISSUE TITLE
Attempting to open devtools causes black screen

### ISSUE THREAD

**Issue by FallingSnow** [Antergos/web-greeter#111]
As soon as I click inspect element the screen goes black with moveable cursor (this just started happening recently). Kind of like with the bug of changing css background images.

Also, 50% of the time when I start my laptop, the greeter goes into slowmo like it used to with the modesetting issue. I have confirmed that I am using the intel driver: `(II) intel(0): Using Kernel Mode Setting driver: i915, version 1.6.0 20160919`. I already have `libvdpau-va-gl` installed.

**Comment by p3lim** [comment]
Same issue as I encountered in #109.

**Comment by FallingSnow** [comment]
Issue seems to be fixed.
