### ISSUE TITLE
meson.build missing

### ISSUE THREAD

**Issue by gigglearrows** [Antergos/web-greeter#115]
using the stable branch.
did the different steps until i got to meson --prefix=/usr --libdir=lib ..
Got the message:
"Error during basic setup:
Neither directory contains a build file meson.build."

using a Debian 9 (stretch) installation

**Comment by gigglearrows** [comment]
Never mind. fixed it. However, how do you uninstall web-greeter when u have used ninja install for it? if i want to remove it in the future

**Comment by gigglearrows** [comment]
Hmm. cant seem to get it to work on debian? Is it enough to clone it and to use checkout, meson, and ninja, then ninja install? Didnt seem to get any errors but when i rebooted the dm didnt change

**Comment by lots0logs** [comment]
> Never mind. fixed it. However, how do you uninstall web-greeter when u have used ninja install for it? if i want to remove it in the future

I dont think ninja has an uninstall command :thinking: 

>Hmm. cant seem to get it to work on debian? Is it enough to clone it and to use checkout, meson, and ninja, then ninja install? Didnt seem to get any errors but when i rebooted the dm didnt change

Did you update lightdm.conf with `lightdm-webkit2-greeter` as the `greeter-session`?

**Comment by gigglearrows** [comment]
Yeah, i just did before you replied and i got it to work. thought it would edit that file itself ^
