### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by pms1969** [Antergos/web-greeter#120]
How do you go about debugging a theme in userspace?  I've got some problems with a theme that seem to be timing based, and locking the screen is a pig that's not yielding anything decisive anyway.  Of course if I just load the theme in the browser, it won't work because there is no lightdm object defined.

Any pointers would be greatly appreciated.

**Comment by lots0logs** [comment]
You can enable debug mode in the config file (located in `/etc/lightdm`) and when the greeter loads it will also load the dev tools window for debugging.

**Comment by lots0logs** [comment]
I forgot to mention that you can run the greeter from within your desktop session if you add the following line to the desktop file for your session located in `/usr/share/xsessions/`:
```
X-LightDM-Allow-Greeter=true
```

You have to log out and log back in after adding that line. Then you can run the greeter from command line.

**Comment by pms1969** [comment]
thanks.  How do I launch the greeter then?  is it just `lightdm --test-mode`?  or do I need to do something with Xephyr first?
Cheers

**Comment by lots0logs** [comment]
Nah, none of that. After you add that line to the session file and log out/in again you can run the greeter directly: 
```
web-greeter
```

**Comment by pms1969** [comment]
:/ hmmm.... I don't have that installed..... I'm guessing I need to clone this repo?

**Comment by lots0logs** [comment]
If you're using the latest stable release then you can run it with this command instead:
```
lightdm-webkit2-greeter
```

**Comment by pms1969** [comment]
thank you.
