### ISSUE TITLE
 Failed to find session configuration web-greeter

### ISSUE THREAD

**Issue by Bryzzle** [Antergos/web-greeter#121]
Hi, I receive the error "Failed to find session configuration web-greeter" in my lightdm.log file whenever the lightdm service is started.
```
[+0.00s] DEBUG: Seat seat0: Failed to find session configuration web-greeter
[+0.00s] DEBUG: Seat seat0: Failed to create greeter session
[+0.00s] DEBUG: Failed to start seat: seat0
```

Here's my lightdm.conf file, not sure if I did something wrong here?

Is the greeter-session supposed to be called something else?

[lightdm.txt](https://github.com/Antergos/web-greeter/files/819152/lightdm.txt)

Let me know what other info could help!

**Comment by lots0logs** [comment]
Hi, did you install the latest stable version or did you install the 3.0 beta version? The greeter-session key in `lightdm.conf` should be set as follows:

* Stable: `lightdm-webkit2-greeter`
* Beta: `web-greeter`

**Comment by Bryzzle** [comment]
I installed 3.0.0beta4. I reverted back to version 2.2.3 (and changed the key back to lightdm-webkit2-greeter), and that works fine. Not sure why the beta isn't working.

**Comment by lots0logs** [comment]
Hmm..I'd need to see the greeter log to see if there are any clues as to what the problem is. You can find the log here: `/var/log/lightdm/seat0-greeter.log`

**Comment by Bryzzle** [comment]
Here is everything in that log
```
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0

```

**Comment by Bryzzle** [comment]
Here is the full lightdm log just in case it might help

```
[+0.00s] DEBUG: Logging to /var/log/lightdm/lightdm.log
[+0.00s] DEBUG: Starting Light Display Manager 1.20.0, UID=0 PID=587
[+0.00s] DEBUG: Loading configuration dirs from /usr/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /usr/local/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /etc/xdg/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /etc/lightdm/lightdm.conf
[+0.00s] DEBUG: Using D-Bus name org.freedesktop.DisplayManager
[+0.00s] DEBUG: Registered seat module local
[+0.00s] DEBUG: Registered seat module xremote
[+0.00s] DEBUG: Registered seat module unity
[+0.00s] DEBUG: Monitoring logind for seats
[+0.00s] DEBUG: New seat added from logind: seat0
[+0.00s] DEBUG: Seat seat0: Loading properties from config section Seat:*
[+0.00s] DEBUG: Seat seat0: Starting
[+0.00s] DEBUG: Seat seat0: Creating greeter session
[+0.00s] DEBUG: Seat seat0: Failed to find session configuration web-greeter
[+0.00s] DEBUG: Seat seat0: Failed to create greeter session
[+0.00s] DEBUG: Failed to start seat: seat0



```

**Comment by ssjems** [comment]
Hi, I got the same error.

I looked into /usr/share/xgreeters.
The filename wasn't web-greeter.desktop but com.antergos.web-greeter.desktop.

So I set greeter-session to com.antergos.web-greeter, and that works fine.

**Comment by lots0logs** [comment]
Hmm..that shouldn't be necessary. The name is inside of the file. It works properly on my system :thinking: I'll look into it.
