### ISSUE TITLE
Slow/Stuttering Login Screen - Ubuntu 16.04

### ISSUE THREAD

**Issue by marioathiel** [Antergos/web-greeter#123]
The login is slow/stuttering on my Ubuntu 16.04. Every Input seems to be in slow motion almost. Any idea what might cause this?

**Comment by lots0logs** [comment]
Hi, Which version are you using? How did you install it?

**Comment by mtr2014** [comment]
Hi, I used the OBS Repo, so the latest Version that is on there.
