### ISSUE TITLE
Setting a theme in LightDM-Webkit config

### ISSUE THREAD

**Issue by NoiSek** [Antergos/web-greeter#125]
I'm being told by users that I should switch my theme to use `webkit_theme` rather than `webkit-theme` when handling `lightdm-webkit2-greeter.conf` due to changes in the web greeter. From some informal testing that does not actually appear to be the case, but I thought that I would verify regardless.

Has `webkit-theme` been deprecated?

**Comment by lots0logs** [comment]
Sorry for the delayed response! Both keys are accepted in the current stable release. The old key has indeed been deprecated in the upcoming 3.0 release. You can view what's coming with 3.0 in the docs for the master branch [here](https://doclets.io/Antergos/web-greeter/master). Let me know if you have any questions.
