### ISSUE TITLE
RFE: Add official Debian package

### ISSUE THREAD

**Issue by berlam** [Antergos/web-greeter#126]
Thank you for the project and supporting Ubuntu already.
I am using Debian (Testing) at work and have been a long-time user of "sbalneav/lightdm-webkit2-greeter".

The compilation of this project was quite easy and I put the build steps inside a docker container (berlam/debian-lightdm-webkit-greeter). My first steps with C and building simple Debian packages (success for me!). Since then a few things have changed after the merge of both projects and builds are getting more complicated (meson, now python, the whither things...) for beginners.

Have you thought of an official Debian build or even submitting to Debian upstream with your expertise?

**Comment by lots0logs** [comment]
Hi, I'm working on getting it packaged in Ubuntu and its looking like getting it into Debian is the best way to do that. Still waiting on a response from my contact at Ubuntu though. Just know that I'm working on it! :wink:
