### ISSUE TITLE
Web-greeter theme throws error after fresh install

### ISSUE THREAD

**Issue by ase1590** [Antergos/web-greeter#129]
I have attempted to put a fresh install of antergos on numerous laptops, and all have thrown errors when attempting the load the greeter theme. it will ask to use the default theme or the fallback theme. 

This particular report comes from my older acer aspire using a mobility radeon HD 4250 card
I enabled debug mode on the greeter, then grabbed the following logs:

Lightdm.log: http://ix.io/q2k
seat0-greeter.log: http://ix.io/q2l

I do not appear to be able to right click the greeter after enabling debug mode in order to bring up the web console either.

**Comment by lots0logs** [comment]
Hi, could you try installing the 3.0 beta version and let me know if it resolves the issue? You can install it with: `sudo pacman -S web-greeter-next'. You'll also need to edit `/etc/lightdm/lightdm.conf` and replace `lightdm-webkit2-greeter` with `web-greeter`.

**Comment by ase1590** [comment]
Still broken. 
1. installed web-greeter-next
1. changed `greeter-session=lightdm-webkit2-greeter` to `greeter-session=web-greeter`
1. Lightdm will throw an error, then terminate. 

Logs: 
Lightdm.log: http://ix.io/q8N
Seat0-greeter.log: http://ix.io/q8O

**Comment by lots0logs** [comment]
From the logs I can see the incorrect theme is being loaded. Could you check `/etc/lightdm/whither.yml` and make sure the theme is set to `default`?

**Comment by ase1590** [comment]
it seems it is set to `default` in `web-greeter.yml`. 

Copy of web-greeter.yml: http://ix.io/q9G

**Comment by lots0logs** [comment]
Could you check to see if the following file exists: `/usr/share/xgreeters/com.antergos.web-greeter.desktop` 

If so, rename it to `web-greeter.desktop`. It looks like the package hasnt been updated since I fixed that file name issue. Sorry about that!

**Comment by ase1590** [comment]
Yeah the fire name issue was the issue. Renaming it allowed it to work just fine. I'm not seeing any notable error outputs other than one relating to caps lock detection, since it looks like that might be a work in progress. 

Otherwise, the theme works fine without it throwing any visible errors.

**Comment by lots0logs** [comment]
Ok, that's great news. I've been holding back the 3.0 release waiting on some upcoming changes in webkitgtk that are needed in order to add support for running 3.0 with webkitgtk. I think if I release it now without webkitgtk support too many people will complain about the Qt dependency :roll_eyes:

**Comment by ase1590** [comment]
So I guess the out-of-the-box theme from a fresh install will just have to stay partially broken till the webkitgtk changes land then?
