### ISSUE TITLE
Tutorial for making theme

### ISSUE THREAD

**Issue by trifirew** [Antergos/web-greeter#134]
I'm interested in making a greeter theme, but don't know how to start with. If someone can provide a how-to or a simple example theme, that will be great. The built-in simple theme does not work on my computer.

**Comment by lots0logs** [comment]
Have you checked out the [theme api docs](https://doclets.io/Antergos/web-greeter/stable)? The [default theme](https://github.com/Antergos/web-greeter/tree/stable/themes/antergos) would be a good example to use as a reference. If you have any specific questions feel free to ask them here :)

**Comment by trifirew** [comment]
Thanks @lots0logs , I'll read the api docs. I've also found a relatively simple theme [https://github.com/omgmog/lightdm-webkit-google](https://github.com/omgmog/lightdm-webkit-google)   
If someone don't know where to start it's probably a good and simple example
