### ISSUE TITLE
high cpu usage in VirtualBox

### ISSUE THREAD

**Issue by frogmouse** [Antergos/web-greeter#139]
I've just begun using Antergos xfce in VirtualBox (on a Lenovo T530).  I generally keep VirtualBox running in one of the four desktops I run in Windows 10.  Other linuxes use very little cpu time when they're idling.  

Antergos (with what I think is _web-greeter)_ takes 39-41% of the cpu when the lock screen is running .
  As soon as I log in, the cpu time drops to around 10%, then to 5 - 6% when I'm actually doing something.   

I poked around and found that I could substitute _litarvan_ for _antergos_ in _lightdm-webkit2-greeter.conf._  Running this reduced my lock-screen cpu usage to 0.4 - 0.6%.  

It is possible that the culprit is the clock animation -- it shivers every now and again.  It's possible that this is associated with #43 "Processes left running ...", but I thought you should know about my experience.

**Comment by lots0logs** [comment]
Let's track this on #140
