### ISSUE TITLE
greeter_config.branding returns different values than greeter_config.get_str(...)

### ISSUE THREAD

**Issue by olemartinruud** [Antergos/web-greeter#143]
As mentionned in the title, when I call `greeter_config.branding` I always get the default object, hence the object that is coded in [GreeterConfig.js](https://github.com/Antergos/web-greeter/blob/stable/src/gresource/js/GreeterConfig.js#L66). However when i use `greeter_config.get_str("branding", "background_images")`, I get the correct value defined in `lightdm-webkit2-greeter.conf`. Despite that `greeter_config.branding` does not work, when I use `greeter_config.greeter` I get access to the settings under the `[greeter]`-section in the `lightdm-webkit2-greeter.conf`. 

These problems leads me to conclude that there must be an error when the `lightdm-webkit2-greeter.conf` file is read. I think its particularly strange that  `greeter_config.greeter` is initialized correctly, but `greeter_config.branding` is not.

To _replicate_ these issuses, add the following lines in a webkit2-theme and run it in debug-mode in the way specified in the [README.md](https://github.com/Antergos/web-greeter/blob/master/README.md). Further you have to change the value of `background` under the `[branding]` section inside your `lightdm-webkit2-greeter.conf` to a **random value**, so that it is not the default `/usr/share/backgrounds`.

```javascript
window.console.log(JSON.stringify(greeter_config.greeter));
window.console.log(JSON.stringify(greeter_config.branding));
window.console.log(greeter_config.get_str("branding", "background_images"));
```

**Comment by lots0logs** [comment]
This is fixed on `master`. The fix will be part of the 3.0 release.
