### ISSUE TITLE
Trouble loading litarvan theme for webkit

### ISSUE THREAD

**Issue by illuminati-RV** [Antergos/web-greeter#144]
I recently installed litarvan on my Manjaro linux 17.0.6 with lightdm-webkit2-greeter configured properly,
I get a blinking screen on loading lightdm. It then asks me to load the default or fallback theme...

[seat0-greeter.log](https://github.com/Antergos/web-greeter/files/1449983/seat0-greeter.log)

This is the log file of the same, pls help me out!

**Comment by olemartinruud** [comment]
This seems to be a theme related problem, hence your issue should only be posted on [Litarvan](https://github.com/Litarvan/lightdm-webkit-theme-litarvan)'s repository. I see that you have already started the exact same issue there, however for future enquirers please post issues where they are relevant.
