### ISSUE TITLE
Multi-monitor order

### ISSUE THREAD

**Issue by Nepoxx** [Antergos/web-greeter#145]
Relates to https://github.com/Antergos/web-greeter/issues/49

How do you configure monitor position in the greeter?

**Comment by lots0logs** [comment]
The greeter doesn't handle it. However, you can configure lightdm to run a script when starting the greeter  (in which you can use `xrandr` command to set the position of your monitors). More details can be found [here](https://wiki.archlinux.org/index.php/LightDM#LightDM_displaying_in_wrong_monitor)
