### ISSUE TITLE
`do_install_dev` seems to be trying to copy a nonexistent folder

### ISSUE THREAD

**Issue by barskern** [Antergos/web-greeter#155]
https://github.com/Antergos/web-greeter/blob/255a84573f28a079047ceb3cd29f486f87e8cdc3/build/utils.sh#L47

Since c9a78365103d16ae7334bf433290dffed0870db3 the `whither` directory has been removed from this version control. Hence I think that the build-instruction to copy this folder into the dev-build is deprecated. Is this assumption correct? I can make a PR with a fix but wanted to ask first.

**Comment by lots0logs** [comment]
Ah, no its not deprecated. You have to run `git submodule update --init` to setup that directory. I just use that as a convenience during development.

**Comment by barskern** [comment]
Ah okay, roger 👍
