### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by synaptiko** [Antergos/web-greeter#48]
I've just installed lightdm & lightdm-webkit2-greeter on XPS13 with QHD+ display and it seems that HiDPI is not detected by webkit. Is it somehow possible to detect it? All native controls are quite small (inputs, buttons, even mouse cursor)…

I'm ok with solution which requires to update my own theme but I'm not sure if it's even possible to know that the "wrapper" is running in HiDPI mode in the first place…

Thanks

**Comment by synaptiko** [comment]
I did small research. If I run Chromium browser on HiDPI diplay, open the console and run: `window.devicePixelRatio` I get `2`. If I switch `lightdm-webkit2-greeter` to debug mode, open the console there and run the same command I get just `1`.

But I've found that in WebKitGTK+ 2.4.9 they added some support for HiDPI: http://webkitgtk.org/2015/05/20/webkitgtk2.4.9-released.html

It seems to me it's support for input, buttons controls etc. But because I don't understand a connection between the greeter and `webkit2gtk` library I'm not sure what can be done. Maybe it would be enough to set some flag somewhere?

Also I've found out that in `/etc/lightdm/lightdm.conf` there is `xserver-command` option and I can "force" the X server to run with some particular DPI but this doesn't help in my case.

I also checked this https://wiki.archlinux.org/index.php/HiDPI but it seems to me like little mess :-(

I hope things above help someone to dig deeper :-)

**Comment by lots0logs** [comment]
Hmm..I will try to dig into this a bit more as soon as I have time. In the meantime try adding the following CSS property to the html element using the developer console. Let me know the result:
```
zoom: 2.0;
```

**Comment by synaptiko** [comment]
It's better but part of the content seems to be missing/cropped. The fields are bigger which is ok :-) As a temporary workaround this could work. Thanks

**Comment by lots0logs** [comment]
Hmm..I wonder if there's a way to take a screenshot from the webkitgtk dev console. It would really help to see what you are seeing..I will try to look into it!

**Comment by FallingSnow** [comment]
Should HiDPI support be provided by the theme? The theme I use does it.

**Comment by synaptiko** [comment]
@FallingSnow So is it "hard-coded" to be HiDPI? Or is there some way how the theme knows it's in HiDPI mode?

**Comment by FallingSnow** [comment]
Do these work? https://css-tricks.com/snippets/css/retina-display-media-query/

Also, the theme I use just goes off the resolution and scales accordingly.

**Comment by synaptiko** [comment]
@FallingSnow Unfortunately media queries doesn't work for me…

**Comment by FallingSnow** [comment]
Strange, `min-width` and `min-height` work for me.

**Comment by synaptiko** [comment]
@FallingSnow: Oh, ok… `min-width` will probably work. I though you are talking about `-webkit-min-device-pixel-ratio`… But `min-width` could be simple solution for now, I'll use it for my theme… Thanks

**Comment by FallingSnow** [comment]
Any progress on HiDPI support?

**Comment by ffhaddad** [comment]
Not sure if this addresses your issue, but all I did to solve the problem was add to the `style.css` file
```
html {
    zoom: 2;
}
```
No clipping for me.

**Comment by jkw** [comment]
@ffhaddad - Path to the file you edited? I got the same issue myself with login-screen being extremely tiny on my Lenovo Yoga 900. QHD+, 3200x1800.

**Comment by ffhaddad** [comment]
@jkw - Apologies, it's been a while and I don't currently have Antergos installed. I'm fairly certain the file was in /usr/share/...

Should be able to do something like:

```
$ cd /usr/share
$ find . -name "style.css"
```

The location of the file should give you good intuition regarding whether or not it's the right one. If it's not in /usr/share location, repeat the same step in the /etc directory.

**Comment by jkw** [comment]
Tested it and html { zoom: 2.0; } worked for me.
File to edit:
`/usr/share/lightdm-webkit/themes/antergos/css/style.css`

Add following code anywhere:
```css
html { zoom: 2.0; }
```

Save file and then, go Super + L and it should work.

**Comment by jkw** [comment]
Did a pull request on this matter now at https://github.com/Antergos/web-greeter/pull/153
