### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by Iambecomeroot** [Antergos/web-greeter#81]
I just installed arch linux on my new laptop. I want to use lightdm greeter for login. The greeter comes up with just a white screen. I tried uninstalling (`pacman -Rns`) both lightdm and lightdm-webkit2-greeter. Nothing works. 

Lighdtm and lightdm-webkit2-greeter versions:

```
extra/lightdm 1:1.18.3-1 [installed]
    A lightweight display manager
aur/lightdm-webkit2-greeter 2.1.6-1 (62, 6.01) [installed: 2.1.4-1]
    A webkit2 greeter for LightDM
```

I have a gtx 960m with this driver:

```
extra/nvidia 370.28-1 [installed]
    NVIDIA drivers for linux
```

My `journalctl -b 0` can be found [here](https://gist.github.com/Marcel-Robitaille/57884c2c096202341822b4d6d6bd45e7).

**Comment by lots0logs** [comment]
Hi, sorry for the delayed response. Are you still have this issue? Based on your log it seems like you would be having problems with more than just this greeter? Does everything else work fine?

**Comment by glubsy** [comment]
I am having this issue too, with a laptop video card (nvidia geforce GTX 670MX, which is Optimus apparently, so I have two VGA entries for nvidia in lspci). 

It seems to me that the greeter segfaults and crashes but I have yet to determine if that's video driver related (nvidia drivers didn't install properly).
I also noticed a `Xlib:  extension "GLX" missing on display ":0"` in seat0-greeter.log but not sure if that's related. I do see this in Xorg.2.log though:
```
[    68.635] (II) LoadModule: "glx"
[    68.635] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[    68.639] (II) Module glx: vendor="NVIDIA Corporation"
[    68.639] 	compiled for 4.0.2, module version = 1.0.0
[    68.639] 	Module class: X.Org Server Extension
[    68.639] (II) NVIDIA GLX Module  375.26  Thu Dec  8 17:59:51 PST 2016
```

Anyway, was going off topic there. 
Here is the forum thread https://forum.antergos.com/topic/5716/white-screen-once-lightdm-starts-lightdm-crashes/

I have the full journalctl logs backed up in case you want them. Hope that helps.

**Comment by rawsh** [comment]
This actually happened to me before, I had to chroot into the system and remove the nvidia package. I think this was because I had optimus, as bumblebee worked.

**Comment by rawsh** [comment]
@lots0logs why close? Three people have this issue already.

**Comment by lots0logs** [comment]
The issue is caused by graphics driver. Its not anything that the greeter has any control over. Sorry!
