### ISSUE TITLE
Default KDE installation greeter (lightdm?) appears to be software accelerated despite nvidia-340xx-libgl et al. being installed?

### ISSUE THREAD

**Issue by lots0logs** [Antergos/web-greeter#89]
@ermo commented on [Wed Apr 27 2016](https://github.com/Antergos/antergos-kde-setup/issues/4)

During graphical login using the default KDE installation greeter, the animations and indeed the general screen response times are so slow that it tends to suggest that software emulation is being used? Is this per design?

Once logged in, the KDE Plasma Desktop is clearly hardware accelerated (Nvidia 8800GT using 340xx drivers).

```
$ pacman -Q |grep lightdm
lightdm 1:1.18.1-1
lightdm-webkit2-greeter 2.1.3-1
$ pacman -Q |grep nvidia
nvidia-340xx-dkms 340.96-10
nvidia-340xx-libgl 340.96-1
nvidia-340xx-utils 340.96-1
$ lspci -k | grep -A 2 -E "(VGA|3D)"
01:00.0 VGA compatible controller: NVIDIA Corporation G92 [GeForce 8800 GT] (rev a2)
        Subsystem: NVIDIA Corporation Device 053c
        Kernel driver in use: nvidia
$ glxinfo | grep direct
direct rendering: Yes
```

(see issue #3 for my xorg log)

---

@srir4m commented on [Wed Nov 23 2016](https://github.com/Antergos/antergos-kde-setup/issues/4#issuecomment-262513588)

sucks doesnt it....
more to the point...i still dont know why sddm wasnt the default display manager...
u can just install sddm and sddm-kcm packages....and then disable lightdm and enable sddm

---

@lots0logs commented on [Wed Nov 23 2016](https://github.com/Antergos/antergos-kde-setup/issues/4#issuecomment-262660157)

@ermo The problem causing lag on some systems was fixed upstream. Please let me know if you still experience the problem on your fully up-to-date system (`sudo pacman -Syyu`)

**Comment by ermo** [comment]
This can be closed now as I no longer care (moved a different distro). But thanks anyway. 👍
