### ISSUE TITLE
Have two gnome on login screen

### ISSUE THREAD

**Issue by eailfly** [Antergos/web-greeter#90]
Have two 'gnome' on the login screen , where can I delete one of theme
![1570503789](https://cloud.githubusercontent.com/assets/3424220/20638212/00093b62-b3db-11e6-84c3-6445dac3299b.jpg)

**Comment by meltdown03** [comment]
One is Wayland, other is Xserver.

**Comment by Nepoxx** [comment]
I have the same thing, on both my installs. I've tried all 4 options (I have the same as the screenshot):

* Gnome: x11
* Gnome: x11 (no idea why there's a second one...)
* Gnome classic: doesn't work, brings me back to greeter
* Gnome on Xorg: x11

How can I get gnome on wayland?

**Comment by meltdown03** [comment]
> How can I get gnome on wayland?
I had to switch to GDM instead of LightDM.
```
pacman -S gdm
sudo systemctl disable lightdm
sudo systemctl enable gdm
```
reboot

Once you get in, open a terminal and type `echo $XDG_SESSION_TYPE`, it should say wayland
